### ISSUE TITLE
Organized files(php, html) into folder

### ISSUE THREAD

**Issue by SusheelThapa** [qaidjoharj53/Blood-Bridge#12]

**Comment by tolik518** [comment]
This can't be done properly with the current state. I mean you could organize the files in folders, but it wouldn't clean the repo up since PHP and HTML are mixed in the PHP files.
It would only make sense if you'd split the code into separate files :)

**Comment by qaidjoharj53** [comment]
Go Ahead! I have assigned the issue to you @SusheelThapa  .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @qaidjoharj53 @rohitagr0310 , @jain-anshika .

**Comment by SusheelThapa** [comment]
@qaidjoharj53 @rohitagr0310 @jain-anshika 
![image](https://github.com/qaidjoharj53/Blood-Bridge/assets/83917129/9ef92a97-5b87-4617-8ba3-b935f27d0b64)


I am facing such issue while registering.

I am on linux so i have used docker to run the project

**Comment by tolik518** [comment]
> @qaidjoharj53 @rohitagr0310 @jain-anshika ![image](https://user-images.githubusercontent.com/83917129/273120043-9ef92a97-5b87-4617-8ba3-b935f27d0b64.png)
> 
> I am facing such issue while registering.
> 
> I am on linux so i have used docker to run the project

You would get the same error if you were using XAMPP, this happens because the author of project hasn't provided us with a database dump - see #9.
To fix this, the author should make a dump of his database and provide it to the repo.
The next step would be writing a PHP file that gets called once someone opens the index.php the first time, so the data can get imported.

**Comment by tolik518** [comment]
> 
> I am facing such issue while registering.
> 
> I am on linux so i have used docker to run the project

I have discovered another problem with the host URL not being exposed to locahost, I'll fix it after work - in like 7 hours :)

**Comment by tolik518** [comment]
The problem @SusheelThapa was talking about was fixed in the #15 PR, it now only needs to be merged.
If you have already tried starting the container before the fix, you'll need to pull the changes after #15 was applied and then `rm -rf database` in the root of the project before starting it another time :)
